apiVersion: v1
kind: Pod
metadata:
  name: cuest-kubelet
spec:
  containers:
    - name: cuest-kubelet
      image: cuestio/cuest-kubelet:latest
      resources:
        limits:
          cpu: 250m
          memory: 200Mi
        requests:
          cpu: 250m
          memory: 200Mi
      imagePullPolicy: Always
      args:
        - /cuest-kubelet
        - --provider
        - cuest
        - --nodename
        - cuest-node
        - --startup-timeout
        - 10s
        - --klog.v
        - "2"
        - --klog.logtostderr
        - --log-level
        - error
        - --no-verify-clients
      env:
        - name: JAEGER_AGENT_ENDPOINT
          value: localhost:6831
        - name: KUBELET_PORT
          value: "10250"
        - name: LOG_LEVEL
          value: debug
        - name: VKUBELET_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: WS_URL
          value: "{{ include "wsUrl" . }}"
        - name: AUTH_URL
          value: "{{ include "authUrl" . }}"
        - name: AUTH_Secret
          value: {{ .Values.AUTH_Secret | quote }}
        - name: AUTH_ID
          value: {{ .Values.AUTH_ID | quote }}
        - name: KUBELET_ID
          value: {{ .Values.KUBELET_ID | quote }}    
        - name: BOOTSTRAP_KUBECONFIG
          value: "/host/var/lib/kubelet/kubeconfig"            
      volumeMounts:
        - name: host-root
          mountPath: /host
  serviceAccountName: cuest-kubelet
  volumes:
    - name: host-root
      hostPath:
        path: /
