apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cuest-kubelet
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get  
  - list
  - get
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - update

# - apiGroups:
#   - certificates.k8s.io
#   resources:
#   - certificatesigningrequests
#   verbs:
#   - create
#   - get
#   - patch
#   - remove
#   - approve
#   - list
# - apiGroups:
#   - certificates.k8s.io
#   resources:
#   - certificatesigningrequests/approval
#   verbs:
#   - update
# - apiGroups:
#   - certificates.k8s.io
#   resources:
#   - signers
#   resourceNames:
#   - kubernetes.io/kubelet-serving
#   verbs:
#   - approve
# - apiGroups:
#   - certificates.k8s.io
#   resources:
#   - certificatesigningrequests
#   resourceNames:
#   - kubernetes.io/kubelet-serving
#   verbs:
#   - sign
#   - approve
# - apiGroups:
#   - ""
#   resources:
#   - serviceaccounts/token
#   verbs:
#   - create
